---
- name: Install packages
  hosts: servers
  become: true
  roles:
    - packages

- name: Configure packages
  hosts: servers
  roles:
    - dotfiles

- name: Reboot server
  hosts: servers
  become: true
  roles:
    - reboot
