---
# Install Go
# https://golang.org/doc/install

- name: Download Go
  unarchive:
    remote_src: yes
    src: "{{ go_download_url }}"
    creates: /usr/local/go
    dest: /usr/local

- name: Include Go binaries in PATH
  lineinfile:
    line: "export PATH=\"$PATH\":{{ go_paths }}"
    path: "/home/{{ lookup('env','USER') }}/.bashrc"
