---
- name: Create installation directory
  file:
    path: /usr/local/node
    state: directory

- name: Download Node
  unarchive:
    remote_src: yes
    src: "{{ node_download_url }}"
    creates: /usr/local/node/bin
    dest: /usr/local/node
    extra_opts:
      - "--strip-component=1"

- name: Include Node binaries in PATH
  lineinfile:
    line: "export PATH=\"$PATH\":{{ node_path }}"
    path: "/home/{{ lookup('env','USER') }}/.bashrc"
