---
- name: Get bash config repo
  git:
    repo: "https://github.com/osoriano/.bashrc.d.git"
    dest: ~/.bashrc.d

# Some OS's have a default bashrc. Append instead of overwriting
# - name: Create bash conf symlink
#   file:
#     src: ~/.bashrc.d/bashrc.sh
#     dest: ~/.bashrc
#     state: link

- name: Source aliases in bashrc
  lineinfile:
    line: "source ~/.bashrc.d/alias.sh"
    path: ~/.bashrc

- name: Source env vars in bashrc
  lineinfile:
    line: "source ~/.bashrc.d/env.sh"
    path: ~/.bashrc
