---
- name: Get bash config repo
  git:
    repo: "https://github.com/osoriano/.bashrc.d.git"
    dest: ~/.bashrc.d

- name: Source .bashrc.d alias
  lineinfile:
    line: "source ~/.bashrc.d/bashrc.sh"
    path: ~/.bashrc
