---
- name: Get vim config repo
  git:
    repo: "https://github.com/osoriano/.vim.git"
    dest: ~/.vim

- name: Get Vundle config
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: ~/.vim/bundle/Vundle.vim
