---
- name: Restart server if needed
  command: /sbin/shutdown -r +1
  args:
    removes: /var/run/reboot-required
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for ssh to come up again
  wait_for_connection:
    connect_timeout: 5
    sleep: 5
    delay: 5
    timeout: 300

